// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piloto.ContextoBaseDatos;

namespace Piloto.Migrations
{
    [DbContext(typeof(PIS_Contexto))]
    partial class PIS_ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Piloto.ContextoBaseDatos.Permiso", b =>
                {
                    b.Property<int>("PermisoID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("PermisoID");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("Piloto.ContextoBaseDatos.RelacionRol_Permiso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("permiso_id");

                    b.Property<int>("rol_id");

                    b.HasKey("id");

                    b.ToTable("RelacionRol_Permiso");
                });

            modelBuilder.Entity("Piloto.ContextoBaseDatos.RelacionUsuario_Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("rol_id");

                    b.Property<int>("usuario_id");

                    b.HasKey("id");

                    b.ToTable("RelacionUsuario_Rol");
                });

            modelBuilder.Entity("Piloto.ContextoBaseDatos.Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descripcion")
                        .HasMaxLength(50);

                    b.Property<string>("nombre")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Piloto.ContextoBaseDatos.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("nombre");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
